<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ctl00bcLoginMainbtnLogin</name>
   <tag></tag>
   <elementGuidId>3df9b251-0864-437d-83af-2a302c21ea09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_bc_LoginMain_btnLogin']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_bc_LoginMain_btnLogin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a21cc79-8c13-4a9f-a064-ad4c08611354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>1da5b16c-e6a8-42f5-9b89-c616489dbd78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$bc$LoginMain$btnLogin</value>
      <webElementGuid>a384a0c7-0620-4950-a472-909e01e3608d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>41c38547-ebb7-41f0-b4bd-defe61d86996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$bc$LoginMain$btnLogin&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, false))</value>
      <webElementGuid>4fc25ea6-7e95-4094-9d00-ab5ce76a3cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_bc_LoginMain_btnLogin</value>
      <webElementGuid>61f4941b-1756-4dd2-8877-8c17f41c2568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_bc_LoginMain_btnLogin&quot;)</value>
      <webElementGuid>34472679-97c8-4af4-862d-459af301baf9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_bc_LoginMain_btnLogin']</value>
      <webElementGuid>537fbe86-5916-49ff-92fc-a99d892c7505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='loginBodyTable']/tbody/tr[2]/td/center/input</value>
      <webElementGuid>36e80b5c-f65b-44d0-bf53-7380b4d4dcc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//center/input</value>
      <webElementGuid>88f11375-194b-464f-a4ba-40e6ccecdae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$bc$LoginMain$btnLogin' and @id = 'ctl00_bc_LoginMain_btnLogin']</value>
      <webElementGuid>e43f0747-0e73-4ae3-81d4-b57d0cba1c6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
