<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ctl00bcLoginMaintxtLogin</name>
   <tag></tag>
   <elementGuidId>bce28478-24f6-4371-8087-85fd243baca7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_bc_LoginMain_txtLogin']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_bc_LoginMain_txtLogin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>21617bc2-6ae8-462a-a334-fc861f4d87e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$bc$LoginMain$txtLogin</value>
      <webElementGuid>77c45c5d-2748-4118-9a20-81d797e3ae27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ec0d71e4-1642-40e0-ae99-1ce86d621cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>64</value>
      <webElementGuid>2102cd58-ca2f-4735-9d52-56df816c6ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_bc_LoginMain_txtLogin</value>
      <webElementGuid>166af956-4b70-4e74-a08b-5e7509e3afbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>f0653a93-7eca-4e5b-9f5e-89ce170367db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_bc_LoginMain_txtLogin&quot;)</value>
      <webElementGuid>c58e41ea-5592-4c30-968b-b770e114af78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_bc_LoginMain_txtLogin']</value>
      <webElementGuid>e1516faa-4d99-40d4-bd7b-47a709b1dd0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='spanLoginTextBox']/input</value>
      <webElementGuid>5c05efda-ccc9-48b1-aa36-34961e8b2ea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>b4f305b5-3ced-4e9f-b122-463bc1dd37c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$bc$LoginMain$txtLogin' and @type = 'text' and @id = 'ctl00_bc_LoginMain_txtLogin']</value>
      <webElementGuid>f5aecfd4-6cca-485f-80f2-0197b0312f03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
