<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ctl00bcMFLQuestionsAnswer1</name>
   <tag></tag>
   <elementGuidId>241bd3d2-4026-4e06-bca8-4a1b76c2881b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_bc_MFLQuestions_Answer1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_bc_MFLQuestions_Answer1111']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a466e4f-97d5-4c0b-be20-a2184b1077d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$bc$MFLQuestions$Answer1</value>
      <webElementGuid>e2273e55-2125-4cd6-b4dd-a5317e2f9ea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>f6553781-ea46-4e7b-97bf-5c33caa49b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>a15e4517-7b82-4f9b-95ed-90471cd2efb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>63e8341d-fa17-42d4-b97d-7afed55293a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_bc_MFLQuestions_Answer1</value>
      <webElementGuid>3dd7451d-063c-44b4-8415-7b18a3af51a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>28013d76-b622-407c-866d-f63b31ab0408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_bc_MFLQuestions_Answer1&quot;)</value>
      <webElementGuid>5ee064fd-2909-45bc-8edc-324df84abda4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_bc_MFLQuestions_Answer1']</value>
      <webElementGuid>f47af2ed-7cd9-41f4-acfe-4ed05bcbce9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='loginContentTD']/table/tbody/tr[2]/td/table/tbody/tr/td[2]/input</value>
      <webElementGuid>beda3242-bc36-4f5f-ad52-6e3cf227dd2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>aadef670-24c1-4a65-8814-1669a2800e7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$bc$MFLQuestions$Answer1' and @type = 'password' and @id = 'ctl00_bc_MFLQuestions_Answer1']</value>
      <webElementGuid>df53e764-8bca-42a3-987f-4a691f569835</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
