<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ctl00bcMFLQuestionsAnswer2</name>
   <tag></tag>
   <elementGuidId>20fc08fd-5e14-4601-9ba4-9d979a20c1b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_bc_MFLQuestions_Answer2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_bc_MFLQuestions_Answer2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ab19e06-63e5-4c46-b174-b7def9b3e759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$bc$MFLQuestions$Answer2</value>
      <webElementGuid>d1da8ad3-6c1e-4ff0-bd19-235d92981b26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>31099730-1b0c-4e0f-b18e-9c971231e246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>1348051c-df33-4600-9a46-4dc8601e74cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>66aeeeac-7bc8-43a4-a8c4-2c8558426366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_bc_MFLQuestions_Answer2</value>
      <webElementGuid>3cc11be1-554e-4ed3-986f-0254976924c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b955d3c7-15a7-406b-8367-21d5f1e70e5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_bc_MFLQuestions_Answer2&quot;)</value>
      <webElementGuid>bbc1fb57-4955-4334-83bb-89b6115a2fd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_bc_MFLQuestions_Answer2']</value>
      <webElementGuid>4b3e0c5a-7d9f-4d9e-a6db-acc54c85a580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='loginContentTD']/table/tbody/tr[2]/td/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>e6a3d64e-34bf-4f0a-9647-5a5bb44abfcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>b936e9aa-9237-491d-8117-a564f46654f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$bc$MFLQuestions$Answer2' and @type = 'password' and @id = 'ctl00_bc_MFLQuestions_Answer2']</value>
      <webElementGuid>82c9c421-0129-457b-ba88-1958ff49cbfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
