<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ctl00bcMFLPasswordPromptbtnSignIn</name>
   <tag></tag>
   <elementGuidId>2b5ebe3c-9fd3-4849-aaf7-4bfe3b9cb5dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_bc_MFLPasswordPrompt_btnSignIn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_bc_MFLPasswordPrompt_btnSignIn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fff4122e-aad3-4184-8bce-2608c5d2978c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>4f8cf6f9-9687-4504-a45e-cc2a8ca68cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$bc$MFLPasswordPrompt$btnSignIn</value>
      <webElementGuid>7239d62f-254d-4018-b465-6653118c5714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>87c88103-4768-4eef-852b-942973551a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$bc$MFLPasswordPrompt$btnSignIn&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, false))</value>
      <webElementGuid>865257d4-42d4-45a3-8d23-97213bef7bbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_bc_MFLPasswordPrompt_btnSignIn</value>
      <webElementGuid>6e0c9984-a255-48bd-93f7-f321de478912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_bc_MFLPasswordPrompt_btnSignIn&quot;)</value>
      <webElementGuid>77821d08-e282-4386-b181-1bafefff6462</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_bc_MFLPasswordPrompt_btnSignIn']</value>
      <webElementGuid>52cf5293-27fb-448b-ab5a-19846f944ef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='ctl00_bc_MFLPasswordPrompt_tdLoginPwd']/input</value>
      <webElementGuid>9b55a754-244c-4625-88bb-60dee3b0476f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>c5d345f0-7bdf-4335-9f88-45d752712acd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$bc$MFLPasswordPrompt$btnSignIn' and @id = 'ctl00_bc_MFLPasswordPrompt_btnSignIn']</value>
      <webElementGuid>8def9cb4-e4d6-4bc6-82e0-5602925e24e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
