<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ctl00bcMFLQuestionsbtnContinue</name>
   <tag></tag>
   <elementGuidId>a536a5c2-a814-484f-800b-987b53bb04a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_bc_MFLQuestions_btnContinue']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_bc_MFLQuestions_btnContinue</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bca17191-db32-462d-bf7d-1b65f8f0028c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>18c5d508-77e9-4474-bbee-9fcfb525f380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$bc$MFLQuestions$btnContinue</value>
      <webElementGuid>59fe5e78-d89d-4769-8445-8062aca7e964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>b39ba11a-e4fc-42de-87be-f78c2d99dd3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$bc$MFLQuestions$btnContinue&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, false))</value>
      <webElementGuid>95bb1460-f2a7-47c4-abf8-0e22cedad4e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_bc_MFLQuestions_btnContinue</value>
      <webElementGuid>f6789b11-cbbf-4eb2-8db1-0f6bfab0e1c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_bc_MFLQuestions_btnContinue&quot;)</value>
      <webElementGuid>9eece1db-d0d6-4563-ac8c-400800aafeab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_bc_MFLQuestions_btnContinue']</value>
      <webElementGuid>a0ee3f9f-9287-4779-bdfd-e06615ab81aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='loginContentTD']/table/tbody/tr[3]/td/center/input</value>
      <webElementGuid>9c41adb3-322a-49b9-b733-14362deb060c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//center/input</value>
      <webElementGuid>36fde8bb-0c86-4b6b-a9cd-99484e6300f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$bc$MFLQuestions$btnContinue' and @id = 'ctl00_bc_MFLQuestions_btnContinue']</value>
      <webElementGuid>306ef51c-77ff-4957-bb55-acfee91f4c8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
