<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ctl00bcMFLPasswordPromptPassword</name>
   <tag></tag>
   <elementGuidId>42528aef-e911-4300-90a8-a283456b4c8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_bc_MFLPasswordPrompt_Password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_bc_MFLPasswordPrompt_Password</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>017dd060-a051-4f54-b115-674f7757255a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$bc$MFLPasswordPrompt$Password</value>
      <webElementGuid>44ab1cf6-13c7-4d93-b1aa-91867c73e903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>bb58654d-973a-4a21-8ba5-84dff463eb60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>b1f63ddf-3d4b-4fd9-8a34-07ade86a8ada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_bc_MFLPasswordPrompt_Password</value>
      <webElementGuid>0cac9e36-ed98-4b3c-9477-d6baa5eb3199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1dc8584e-1180-4da6-851c-2c2830df3c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_bc_MFLPasswordPrompt_Password&quot;)</value>
      <webElementGuid>ac23db7f-842b-4985-be01-80edc50a0e12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_bc_MFLPasswordPrompt_Password']</value>
      <webElementGuid>06e9388e-3615-4ba7-8af7-16915ad00823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_bc_MFLPasswordPrompt_divPwd']/input</value>
      <webElementGuid>662de432-bdeb-48a3-b271-10c85594dab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/input</value>
      <webElementGuid>5f86f8d4-096c-469b-9bb3-17215998b8a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$bc$MFLPasswordPrompt$Password' and @type = 'password' and @id = 'ctl00_bc_MFLPasswordPrompt_Password']</value>
      <webElementGuid>609e6dbb-4de5-4ea7-915c-c06bb323219b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
