<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>168cc995-1dc9-45d7-b9e5-f68028128d2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='Table2']/tbody/tr/td/table/tbody/tr/td/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;ML-QA&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>42847322-c4c9-41aa-9c07-2ffd3ba7d9db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>ML-QA</value>
      <webElementGuid>e47264a7-50fa-4f93-b17a-ea99a1099832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/inc/FileDBReader.aspx?enc2=3N-LnjQWmDGCSw5N4k_uS0bMeSeU7zfWg6AYKfEaTTg28sSUzd1moX1TRW2Mp7N1bqLtePpnEgk9DZ6_fVWPXnzF4DDlBtOpX6SUWtaKBujXVPISV5Zi6Ya6zsoGawBJsrjbQcfm09htLYFu1QY53vBrcnSySb3monwtehD8k_tJiG00p3-2guLu-prQpvSgFdXzEHHF9JsZ9pD-9USsIC4ang5F5gfelmjxphKkkPpddutWTJuW_qzOCbm9kcNut61MM_VmcOfAdZRnkKxGsX9uIXw36ku9aKEN9iQSCkqy51Ok6gDm7Li5W4p1C8YXePAbmUK0E_t2VCoE5isWrdjTFQVVUgAd_cUYJ46Vrio</value>
      <webElementGuid>820bf58a-a334-4cb3-8c59-36b86a2ae6a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fcefbfe2-bfe7-44bf-9758-0986bdc3bbd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Table2&quot;)/tbody[1]/tr[1]/td[1]/table[@class=&quot;ie78GapHack&quot;]/tbody[1]/tr[1]/td[1]/img[1]</value>
      <webElementGuid>6ab90cea-0122-48ea-8bd0-4c755dcbd3b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='Table2']/tbody/tr/td/table/tbody/tr/td/img</value>
      <webElementGuid>bb30f4bf-8df3-4776-9c18-e4cce171d363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='ML-QA']</value>
      <webElementGuid>ad0c0250-5c53-46f0-b702-ef09e7a2a66a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>6e4a8433-85d2-4ca5-b9b9-15182e3cae1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'ML-QA' and @src = '/inc/FileDBReader.aspx?enc2=3N-LnjQWmDGCSw5N4k_uS0bMeSeU7zfWg6AYKfEaTTg28sSUzd1moX1TRW2Mp7N1bqLtePpnEgk9DZ6_fVWPXnzF4DDlBtOpX6SUWtaKBujXVPISV5Zi6Ya6zsoGawBJsrjbQcfm09htLYFu1QY53vBrcnSySb3monwtehD8k_tJiG00p3-2guLu-prQpvSgFdXzEHHF9JsZ9pD-9USsIC4ang5F5gfelmjxphKkkPpddutWTJuW_qzOCbm9kcNut61MM_VmcOfAdZRnkKxGsX9uIXw36ku9aKEN9iQSCkqy51Ok6gDm7Li5W4p1C8YXePAbmUK0E_t2VCoE5isWrdjTFQVVUgAd_cUYJ46Vrio']</value>
      <webElementGuid>af527d1f-9263-4a31-9792-98b63d4b4446</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
